api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    exception_to_status:
        App\Exception\DisableToDelete: 404
        App\Exception\ErrorMessageException: 500
    # enable_docs: false
    # enable_entrypoint: false