nelmio_cors:
    defaults:
        allow_origin: ['https://7e-sky.github.io']
        allow_methods: ['GET', OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['content-type', 'authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['https://7e-sky.github.io']
            allow_methods: ['GET', OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['content-type', 'authorization']
            expose_headers: ['Link']
            max_age: 3600
