swiftmailer:
    default_mailer: mailer_admin
    mailers:
        mailer_adherent:
            url: '%env(MAILER_URL)%'
            spool: { type: 'memory' }
        mailer_admin:
            url: '%env(MAILER_URL_ADMIN)%'
            spool: { type: 'memory' }
