vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        demande:
            uri_prefix: /attachement/demandeAchat
            upload_destination: '%kernel.project_dir%/public/attachement/demandeAchat'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true