#swiftmailer:
#    mailers:
#        mailer_adherent:
#            delivery_addresses: ['youness.arbouh1@gmail.com']
#        mailer_admin:
#            delivery_addresses: ['youness.arbouh1@gmail.com']