swiftmailer:
    mailers:
        mailer_adherent:
            delivery_addresses: ['it.3findustrie@gmail.com']
        mailer_admin:
            delivery_addresses: ['it.3findustrie@gmail.com']
        mailer_no_reply:
            delivery_addresses: ['it.3findustrie@gmail.com']